version: '3'

services:
  mm:
    image: mysql-manager:v0.1
    command: /app/tests/setup.sh
    environment: 
      MYSQL_S1_HOST: mysql-s1
      MYSQL_S2_HOST: mysql-s2
      MYSQL_ROOT_PASSWORD: root
      MYSQL_REPL_PASSWORD: repl
      PROXYSQL_HOST: proxysql
      PROXYSQL_PASSWORD: pwd 
      PROXYSQL_MON_PASSWORD: pwd
    volumes:
      - '.:/app:rw'
  mysql-s1:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s1.cnf:/etc/mysql/conf.d/mysql.cnf'
  mysql-s2:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s2.cnf:/etc/mysql/conf.d/mysql.cnf'
  proxysql: 
    image: hub.hamdocker.ir/proxysql/proxysql:2.6.2
    volumes:
      - './tests/config/proxysql.cnf:/etc/proxysql.cnf'
