version: '3'

services:
  mm:
    # image: registry.hamdocker.ir/public/mysql-manager:b212be8e
    build: .
    environment: 
      ETCD_HOST: etcd
      ETCD_USERNAME: mm
      ETCD_PASSWORD: password
      ETCD_PREFIX: mm/cluster1/
    volumes:
    - './tests/config/mm-config-mysql-2.yaml:/etc/mm/cluster-spec.yaml'
  etcd: 
    image: quay.hamdocker.ir/coreos/etcd:v3.5.9-amd64
    command: 
        - etcd
        - --data-dir=/var/lib/etcd
        - --name=mm-etcd
        - --advertise-client-urls=http://etcd:2379
        - --initial-cluster-token=etcd-cluster
        - --initial-cluster-state=new
        - --listen-client-urls=http://0.0.0.0:2379
        - --listen-metrics-urls=http://0.0.0.0:2381
        - --listen-peer-urls=http://0.0.0.0:2380
        - --auto-compaction-mode=revision
        - --auto-compaction-retention=5
    # volumes:
    # - ./etcd-data/:/var/lib/etcd/
  mysql-s1:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s1.cnf:/etc/mysql/conf.d/mysql.cnf'
      # - './mysql-s1-data:/var/lib/mysql'
    restart: always
  mysql-s2:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s2.cnf:/etc/mysql/conf.d/mysql.cnf'
      # - './mysql-s2-data:/var/lib/mysql'
    restart: always
  mysql-exporter-s1: 
    image: hub.hamdocker.ir/prom/mysqld-exporter:v0.15.1
    command: "--config.my-cnf=/etc/my.cnf"
    volumes:
      - './tests/config/mysql-exporter-s1.cnf:/etc/my.cnf'
  mysql-exporter-s2: 
    image: hub.hamdocker.ir/prom/mysqld-exporter:v0.15.1
    command: "--config.my-cnf=/etc/my.cnf"
    volumes:
      - './tests/config/mysql-exporter-s2.cnf:/etc/my.cnf'
  proxysql: 
    image: hub.hamdocker.ir/proxysql/proxysql:2.6.2
    volumes:
      - './tests/config/proxysql.cnf:/etc/proxysql.cnf'
      # - './proxysql-data:/var/lib/proxysql'
  promtheus: 
    image: hub.hamdocker.ir/prom/prometheus
    volumes: 
    - './tests/config/prometheus.yaml:/etc/prometheus/prometheus.yml'
    - './tests/config/rules.yaml:/etc/prometheus/rules.yaml'
    ports: 
    - "9090:9090"
