version: '3'

services:
  # mm:
  #   # image: registry.hamdocker.ir/public/mysql-manager:b212be8e
  #   build: .
  #   command: --nodes 1 
  #   environment: 
  #     MYSQL_S1_HOST: mysql-s1
  #     MYSQL_S2_HOST: mysql-s2
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_NONPRIV_USER: hamadmin
  #     MYSQL_NONPRIV_PASSWORD: password
  #     MYSQL_REPL_PASSWORD: repl
  #     MYSQL_EXPORTER_PASSWORD: exporter
  #     PROXYSQL_HOST: proxysql
  #     PROXYSQL_PASSWORD: pwd 
  #     PROXYSQL_MON_PASSWORD: pwd
    # volumes:
    # - './tests/config/mm-config-mysql-2.ini:/etc/mm/config.ini'
    # - './tests/config/mm-config-mysql-1.ini:/etc/mm/config-mysql-1.ini'
  etcd: 
    image: quay.hamdocker.ir/coreos/etcd:v3.5.9-amd64
    command: 
        - etcd
        - --data-dir=/var/lib/etcd
        - --name=mm-etcd
        - --advertise-client-urls=http://etcd:2379
        - --initial-cluster-token=etcd-cluster
        - --initial-cluster-state=new
        - --listen-client-urls=http://0.0.0.0:2379
        - --listen-metrics-urls=http://0.0.0.0:2381
        - --listen-peer-urls=http://0.0.0.0:2380
        - --auto-compaction-mode=revision
        - --auto-compaction-retention=5
  mysql-s1:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s1.cnf:/etc/mysql/conf.d/mysql.cnf'
    restart: always
  mysql-s2:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s2.cnf:/etc/mysql/conf.d/mysql.cnf'
    restart: always
  mysql-exporter-s1: 
    image: hub.hamdocker.ir/prom/mysqld-exporter:v0.15.1
    command: "--config.my-cnf=/etc/my.cnf"
    volumes:
      - './tests/config/mysql-exporter-s1.cnf:/etc/my.cnf'
    ports: 
    - 9105:9104
  mysql-exporter-s2: 
    image: hub.hamdocker.ir/prom/mysqld-exporter:v0.15.1
    command: "--config.my-cnf=/etc/my.cnf"
    volumes:
      - './tests/config/mysql-exporter-s2.cnf:/etc/my.cnf'
    ports: 
    - 9104:9104
  proxysql: 
    image: hub.hamdocker.ir/proxysql/proxysql:2.6.2
    volumes:
      - './tests/config/proxysql.cnf:/etc/proxysql.cnf'
  promtheus: 
    image: hub.hamdocker.ir/prom/prometheus
    volumes: 
    - './tests/config/prometheus.yaml:/etc/prometheus/prometheus.yml'
    - './tests/config/rules.yaml:/etc/prometheus/rules.yaml'
    ports: 
    - "9090:9090"
