version: '3'

services:
  mm:
    image: registry.hamdocker.ir/public/mysql-manager:v0.2.0
    command: sleep inf
    environment: 
      MYSQL_S1_HOST: mysql-s1
      MYSQL_S2_HOST: mysql-s2
      MYSQL_ROOT_PASSWORD: root
      MYSQL_REPL_PASSWORD: repl
      MYSQL_EXPORTER_PASSWORD: exporter
      PROXYSQL_HOST: proxysql
      PROXYSQL_PASSWORD: pwd 
      PROXYSQL_MON_PASSWORD: pwd
    volumes:
      - '.:/app:rw'
  mysql-s1:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s1.cnf:/etc/mysql/conf.d/mysql.cnf'
  mysql-s2:
    image: hub.hamdocker.ir/library/mysql:8.0.35-bullseye
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './tests/config/mysql-s2.cnf:/etc/mysql/conf.d/mysql.cnf'
  mysql-exporter-s2: 
    image: hub.hamdocker.ir/prom/mysqld-exporter:v0.15.1
    command: "--config.my-cnf=/etc/my.cnf"
    volumes:
      - './tests/config/mysql-exporter-s2.cnf:/etc/my.cnf'
    ports: 
    - 9104:9104
  proxysql: 
    image: hub.hamdocker.ir/proxysql/proxysql:2.6.2
    volumes:
      - './tests/config/proxysql.cnf:/etc/proxysql.cnf'
  promtheus: 
    image: hub.hamdocker.ir/prom/prometheus
    volumes: 
    - './tests/config/prometheus.yaml:/etc/prometheus/prometheus.yml'
    - './tests/config/rules.yaml:/etc/prometheus/rules.yaml'
    ports: 
    - "9090:9090"
