name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${github.GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.REGISTRY_URL }}/mysql-manager:main ${{ vars.REGISTRY_URL }}/mysql-manager:${{ SHORT_SHA }}
